### PR TITLE
feat: display hero illusions

### PR DESCRIPTION
**Pull request by vlejd**
Addresses https://github.com/timkurvers/redota/issues/32 . 
Illusions have bluish icons now.

### CODE REVIEW

**Comment by timkurvers** [comment]
Awesome, thanks! Found [this issue](https://github.com/skadistats/clarity/issues/177) on the Clarity parser, which seems to suggest that `m_hReplicatingOtherHeroModel` may also be used by Morphling when morphed into other heroes. Did you check that by any chance?

Could you also run `npm run lint`? Ideally the PR should have run that automatically, but I may have set that up incorrectly 🤔

**Comment by vlejd** [comment]
lint done, sorry I forgot.

**Comment by vlejd** [comment]
Regarding Morphling, yes. When he is ulted he will also be classified as illusion (min 30 from Morphling for example). The current implementation is pretty consistent with what you would see in normal Dota replay.

**Comment by timkurvers** [comment]
Awesome, thanks! 👍

**Pull request merged**
