### PR TITLE
Added 7.29 map and minimap assets.

### PR DESCRIPTION
**Pull request by likwidoxigen**
Nothing fancy here just added the 7.29 assets. 
I figure it makes sense to switch to the current patch maps and then back-port older-maps with the pick by date. 
If you'd rather not go that route just decline the request and then I'll remove it.

### CODE REVIEW

**Comment by timkurvers** [comment]
Awesome! That sounds like a good approach.

The 7.23 images originated from the Dota 2 wiki on Gamepedia. Is that the case for these files too?

**Comment by likwidoxigen** [comment]
These files I generated. Devilesk (the original person who would generate the map) left some great instructions for the process. I took the old map and lined up fountains (to make sure structures placed correctly) and then double checked their placement with a current replay.
As far as the minimap I did custom scalling on the full size map over the existing mini-map to make sure everything lined up. It isn't specifically the mini-map asset from Dota2, just a scaled full size map, but it works the same. I'm still figuring out how to find/extract the real minimap.

**Comment by timkurvers** [comment]
Ah excellent! If you like we can add a note to the README that you are the creator of these assets specifically.

One minor thing: it seems Husky did not enforce commit messages to adhere to the guidelines for you, would you like to change your commit message? Alternatively, I might be able to do that in the merge/squash process.

**Comment by likwidoxigen** [comment]
Sure thing, that would be great :) 

Sorry about that. Looking now I see that I don't have the HUSKY_GIT_PARAMS var defined anywhere. Is there a missing .env sample file? After we sort this out I'd be happy to work up a contributors guide as well.

**Comment by timkurvers** [comment]
> Sorry about that. Looking now I see that I don't have the HUSKY_GIT_PARAMS var defined anywhere. Is there a missing .env sample file? After we sort this out I'd be happy to work up a contributors guide as well.

These git hooks should in theory have installed itself automatically on `npm install` as part of husky.

At least they do here on my end:

```
$ npm install
...
> husky@4.3.0 install /redota/node_modules/husky
> node husky install
husky > Setting up git hooks
husky > Done
```

**Comment by likwidoxigen** [comment]
Ahh ok, that was my bad. Needed to have git installed on the docker image.  It did take me far too long to think of looking at a prior commit for how to structure the message but it's installed and verified working.
Re-wording could probably be done at merge? At this point I'd probably have to wipe the branch and submit a new pull request.  Let me know if you want me to wipe and re-submit.

Thanks!

**Comment by timkurvers** [comment]
Ah, that makes sense! No worries, I'll have a look.

**Comment by timkurvers** [comment]
Thanks! If you would like to be credited in the README in a certain way, feel free to open a PR for that. Otherwise I'll do that a bit later this week.

**Comment by timkurvers** [comment]
Added the resource note to the README in https://github.com/timkurvers/redota/commit/051749c20fd47949a7f0190a5155cf3fc798e323.

**Pull request merged**
